// @include('../../node_modules/babel-polyfill/dist/polyfill.js')
// @include('../../node_modules/bowser/bowser.js')
// @include('../../node_modules/svg4everybody/dist/svg4everybody.js')
// @include('../../node_modules/jquery/dist/jquery.js')
// @include('../../node_modules/jquery-scrollto/out/lib/jquery-scrollto.js')
// @include('../../node_modules/fancybox/dist/js/jquery.fancybox.js')
// @include('../../node_modules/wow.js/dist/wow.js')
